name: temperature
description: A flutter project based on TDD

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  dartz: ^0.10.1
  geolocator: ^9.0.2
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  mocktail: ^0.3.0
  get_it: ^7.2.0
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:

  uses-material-design: true

  assets:
    - images/

